AWSTemplateFormatVersion: '2010-09-09'
Description: Echo lambda
Resources:
  ApiLambdaPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${EchoLambda}:PROD
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EchoAPI}/*/*/*
    Type: AWS::Lambda::Permission
  EchoAPI:
    Properties:
      DefinitionBody:
        info:
          title:
            Ref: AWS::StackName
        paths:
          /echo/{name}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EchoLambda.Arn}:PROD/invocations
        schemes:
        - https
        swagger: '2.0'
      StageName: prod
    Type: AWS::Serverless::Api
  EchoLambda:
    Properties:
      CodeUri: s3://lambda-bucket-nachoelcalvo/95701c30c5e31d56b3b92c6552c89aba
      Environment:
        Variables:
          GREETING: Hola
      Events:
        ApiEvents:
          Properties:
            Method: GET
            Path: /echo/{name}
            RestApiId:
              Ref: EchoAPI
          Type: Api
      Handler: org.personal.EchoLambdaGateway::handler
      MemorySize: 512
      Runtime: java8
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
